### ISSUE TITLE
Notifications not work

### ISSUE THREAD

**Issue by zhil** [abiczo/github-notifier#19]
Looks like package do not work. I execute it with command 
```
github-notifier -i 60 -v
```
I got such a log
```
[INFO] 04 жов 12:43:45
github-notifier is not capable of using hyperlinks
[INFO] 04 жов 12:43:45
Creating system tray icon
[INFO] 04 жов 12:43:45
Fetching feed http://github.com/zhil.private.atom?token=***
[INFO] 04 жов 12:43:45
Enabling feeds organizations
[INFO] 04 жов 12:43:46
Fetching feed http://github.com/zhil.private.actor.atom?token=***
[INFO] 04 жов 12:44:47
Fetching feed http://github.com/zhil.private.atom?token=****
[INFO] 04 жов 12:44:48
Fetching feed http://github.com/zhil.private.actor.atom?token=***
```

When I try to open that page manually - I got just empty page.

**Comment by abiczo** [comment]
If you go to your feed page on github and click on the "Subscribe to your news feed" link does that show you the atom feed? Can you make sure to use the same token from that url?

**Comment by zhil** [comment]
@abiczo thanks for your answer.

sorry, I cant find my "feed page". I dont see anythink like that on https://github.com/zhil/ OR on https://github.com/notifications.

Can you please give me more details about it?

**Comment by abiczo** [comment]
Sorry I should have been more clear. I just meant https://github.com The link I mentioned should be in the right hand column. Let me know if you do t see it though and I'll try to send you a screenshot.

**Comment by zhil** [comment]
@abiczo oh, thanks, got you.
I used token from https://github.com/settings/tokens

should work now, will test a bit later

**Comment by abiczo** [comment]
Hopefully it worked out so closing this out now. Let me know if it still doesn't work.
